module.exports = {
  extends: ['next/core-web-vitals', 'eslint:recommended', 'prettier', 'turbo'],
  plugins: ['unused-imports', '@typescript-eslint'],
  rules: {
    'react/prop-types': 0,
    'react/jsx-uses-react': 0,
    'react/react-in-jsx-scope': 0,
    'react/self-closing-comp': 'warn',
    'react/prefer-stateless-function': 'error',
    'react/button-has-type': 0,
    'react/no-unused-prop-types': 'error',
    'react/jsx-pascal-case': 'error',
    'turbo/no-undeclared-env-vars': 0,
    'react/jsx-no-script-url': 'error',
    'react/no-danger': 'error',
    'react/no-danger-with-children': 'error',
    'react/no-unstable-nested-components': ['error', { allowAsProps: true }],
    'react/destructuring-assignment': ['error', 'always'],
    'react/jsx-key': [
      'error',
      {
        checkFragmentShorthand: true,
        checkKeyMustBeforeSpread: true,
        warnOnDuplicates: true,
      },
    ],
    'react/jsx-no-useless-fragment': 'warn',
    'react/jsx-curly-brace-presence': 'warn',
    'react/no-typos': 'warn',
    'react/display-name': 'warn',
    'react/jsx-one-expression-per-line': 0,
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': 'error',
    'no-case-declarations': 0,
    'no-inner-declarations': 0,
    'no-extra-boolean-cast': 0,
    'no-irregular-whitespace': 0,
    'prefer-const': 0,
    'no-use-before-define': ['error', { functions: false }],
    'no-unused-vars': 0,
    'no-undef': 0,
    'import/no-anonymous-default-export': 0,
    'unused-imports/no-unused-vars': 1,
    'unused-imports/no-unused-imports': 1,
  },
  overrides: [
    {
      files: ['*.d.ts'],
      rules: {
        'unused-imports/no-unused-vars': 0,
      },
    },
  ],
};
